services:
  postgres:
    image: postgres:latest
    container_name: cricapp-postgres
    environment:
      POSTGRES_DB: cricapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cricapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cricapp.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "7070:80"